name: Tests and linting

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron:  '0 3 * * *'

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['7.2', '7.3', '7.4']
        dependencies: ['']
        include:
          - { php-version: '7.2', dependencies: '--prefer-lowest' }

    name: PHP ${{ matrix.php-version }} ${{ matrix.dependencies }} (unit tests)

    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, zip
          coverage: xdebug

      - name: Install dependencies
        run: composer update --no-interaction --no-progress ${{ matrix.dependencies }}

      - name: Run tests
        run: |
          vendor/bin/phpunit --coverage-clover coverage-clover.xml

      - name: Submit coverage to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer global require --dev php-coveralls/php-coveralls
          ~/.composer/vendor/bin/php-coveralls -v

  codestyle:
    name: "Code style and static analysis"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, intl

      - name: Install dependencies
        run: composer update --no-interaction --no-progress

      - name: Lint
        run: composer lint

      - name: Run checks
        run: composer analyze

  markdown-link-check:
    name: "Markdown link check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-verbose-mode: 'yes'
